spring.application.name=monitoring app

#promethes configuration

management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=*

#http://localhost:8080/actuator
#http://localhost:8080/actuator/prometheus