spring:
  application:
    name: lacon
  datasource:
    url: jdbc:postgresql://localhost:5432/j2
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
      database: POSTGRESQL
      show-sql: true

server:
  port: 8080

camunda.bpm.admin-user:
  id: admin
  password: admin

camunda:
  bpm:
    generic-properties:
      properties:
        enforceHistoryTimeToLive: false
  history-level: full