spring:
  application:
    name: lacon
  datasource:
    url: jdbc:postgresql://localhost:5432/j1
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8080

camunda.bpm.admin-user:
  id: admin
  password: admin

camunda:
  bpm:
    generic-properties:
      properties:
        enforceHistoryTimeToLive: false